package com.example.meto;

public class CityList {
    public static final String[] CITIES = {
            // # Top Tier Cities (Most Searched/Visited)
    "Bangkok", "Istanbul", "London", "Hong Kong", "Mecca",
            "Antalya", "Dubai", "Macau", "Paris", "Kuala Lumpur",
            "New York", "Singapore", "Tokyo", "Rome", "Barcelona",
            "Delhi", "Shanghai", "Shenzhen", "Amsterdam", "Berlin",
            "Madrid", "Los Angeles", "Cairo", "Prague", "Mexico City",
            "Vienna", "Las Vegas", "Toronto", "Sydney", "Seoul",
            "Moscow", "Miami", "Athens", "Budapest", "Lisbon",
            "Moscow", "Venice", "Florence", "Chicago", "Houston",
            "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas",
            "San Jose", "Austin", "Vancouver", "Portland", "Seattle",
            "San Francisco", "Boston", "Washington", "Denver", "Atlanta",
            "Miami", "Orlando", "New Orleans", "Nashville", "Memphis",
            "Detroit", "Minneapolis", "Cleveland", "Cincinnati", "Columbus",
            "Sacramento", "Long Beach", "Kansas City", "Mesa", "Arlington",

         //   # European Cities
    "Stockholm", "Copenhagen", "Oslo", "Helsinki", "Dublin",
            "Warsaw", "Krakow", "Prague", "Budapest", "Sofia",
            "Belgrade", "Zagreb", "Ljubljana", "Bucharest", "Bratislava",
            "Athens", "Lisbon", "Porto", "Barcelona", "Madrid",
            "Valencia", "Seville", "Malaga", "Bilbao", "Granada",
            "Milan", "Venice", "Florence", "Rome", "Naples",
            "Turin", "Genoa", "Bologna", "Verona", "Padua",
            "Nice", "Lyon", "Marseille", "Paris", "Strasbourg",
            "Brussels", "Antwerp", "Amsterdam", "Rotterdam", "The Hague",
            "Zurich", "Geneva", "Bern", "Lucerne", "Basel",
            "Vienna", "Salzburg", "Graz", "Innsbruck", "Berlin",
            "Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart",

          //  # Asian Cities
    "Bangkok", "Phuket", "Pattaya", "Chiang Mai", "Da Nang",
            "Ho Chi Minh City", "Hanoi", "Phnom Penh", "Siem Reap", "Kuala Lumpur",
            "Penang", "Johor Bahru", "Kuching", "Kota Kinabalu", "Singapore",
            "Jakarta", "Surabaya", "Bandung", "Medan", "Denpasar",
            "Bali", "Lombok", "Manila", "Cebu", "Davao",
            "Bangkok", "Phuket", "Chiang Mai", "Krabi", "Pattaya",
            "Hong Kong", "Macau", "Shenzhen", "Guangzhou", "Shanghai",
            "Beijing", "Xi'an", "Chengdu", "Chongqing", "Hangzhou",
            "Suzhou", "Nanjing", "Wuhan", "Shenyang", "Harbin",
            "Tokyo", "Osaka", "Kyoto", "Hiroshima", "Nagasaki",
            "Yokohama", "Kobe", "Fukuoka", "Sapporo", "Sendai",
            "Seoul", "Busan", "Incheon", "Daegu", "Daejeon",
            "Gwangju", "Ulsan", "Jeju", "Bangkok", "Phuket",
            "Hanoi", "Ho Chi Minh City", "Da Nang", "Phnom Penh", "Siem Reap",
            "Vientiane", "Luang Prabang", "Phuket", "Krabi", "Pattaya",
            "Jaipur", "Delhi", "Agra", "Mumbai", "Pune",
            "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Goa",
            "Varanasi", "Udaipur", "Rajasthan", "Kerala", "Goa",

       //     # Middle East & Africa
    "Dubai", "Abu Dhabi", "Doha", "Riyadh", "Jeddah",
            "Medina", "Mecca", "Muscat", "Kuwait City", "Manama",
            "Beirut", "Jerusalem", "Tel Aviv", "Amman", "Cairo",
            "Alexandria", "Giza", "Luxor", "Aswan", "Hurghada",
            "Lagos", "Nairobi", "Cape Town", "Johannesburg", "Accra",
            "Marrakech", "Casablanca", "Fes", "Tangier", "Agadir",
            "Tunis", "Algiers", "Oran", "Constantine", "Sfax",
            "Khartoum", "Addis Ababa", "Kampala", "Dar es Salaam", "Zanzibar",
            "Mombasa", "Harare", "Lusaka", "Luanda", "Kinshasa",

          //  # Americas
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
            "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
            "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte",
            "San Francisco", "Fresno", "Sacramento", "Long Beach", "Kansas City",
            "Mesa", "Arlington", "Tulsa", "Tampa", "Aurora",
            "New Orleans", "Anaheim", "Miami", "Orlando", "Las Vegas",
            "Nashville", "Memphis", "Boston", "Seattle", "Denver",
            "Washington", "Atlanta", "Minneapolis", "Cleveland", "Cincinnati",
            "Detroit", "Portland", "Tucson", "Albuquerque", "Bakersfield",
            "Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton",
            "Ottawa", "Winnipeg", "Quebec City", "Mississauga", "Brampton",
            "Mexico City", "Guadalajara", "Cancun", "Acapulco", "Puerto Vallarta",
            "Cabo San Lucas", "Mazatlan", "Los Cabos", "Merida", "Playa del Carmen",
            "Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata",
            "Rio de Janeiro", "Sao Paulo", "Salvador", "Fortaleza", "Manaus",
            "Brasilia", "Curitiba", "Porto Alegre", "Recife", "Belo Horizonte",
            "Lima", "Arequipa", "Cusco", "Machu Picchu", "Nazca",
            "Quito", "Guayaquil", "Cuenca", "Bogota", "Medellin",
            "Cali", "Cartagena", "Santa Marta", "Barranquilla", "Buenaventura",
            "Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Ciudad Guayana",
            "Santiago", "Valparaiso", "Concepcion", "La Serena", "Valdivia",
            "Asuncion", "Encarnacion", "Montevideo", "Punta del Este", "Salto",
            "La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro",
            "Havana", "Santiago de Cuba", "Trinidad", "Cienfuegos", "Matanzas",
            "Panama City", "David", "Colon", "Panama Canal", "Bocas del Toro",
            "San Jose", "San Salvador", "Tegucigalpa", "Managua", "San Juan",

          //  # Oceania & Pacific
    "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide",
            "Gold Coast", "Cairns", "Hobart", "Darwin", "Canberra",
            "Auckland", "Wellington", "Christchurch", "Queenstown", "Rotorua",
            "Fiji", "Nadi", "Suva", "Honolulu", "Maui",
            "Hilo", "Kona", "Pago Pago", "Apia", "Nuku'alofa",

            //# Additional High-Search Cities
    "Taipei", "Tainan", "Taichung", "Kaohsiung", "Bangkok",
            "Chiang Mai", "Pattaya", "Phuket", "Krabi", "Koh Samui",
            "Koh Phangan", "Railay", "Phi Phi", "Similan", "Satun",
            "Trang", "Nakhon Si Thammarat", "Surat Thani", "Phang Nga", "Ranong",
            "Chumphon", "Prachuap Khiri Khan", "Hua Hin", "Cha-am", "Samut Prakan",
            "Nonthaburi", "Nakhon Pathom", "Saraburi", "Khon Kaen", "Korat",
            "Surin", "Si Sa Ket", "Yasothon", "Amnat Charoen", "Ubon Ratchathani",
            "Ratchaburi", "Kanchanaburi", "Tak", "Lampang", "Lamphun",
            "Sukhothai", "Uttaradit", "Kamphaeng Phet", "Phichit", "Phetchabun",
            "Loei", "Nong Khai", "Udon Thani", "Sakon Nakhon", "Nakhon Phanom",
            "Mukdahan", "Amnat Charoen", "Roi Et", "Maha Sarakham", "Kalsin",
            "Chaiyaphum", "Yasothon", "Si Sa Ket", "Amnat Charoen", "Ubon Ratchathani",
            "Phuket", "Krabi", "Satun", "Trang", "Phang Nga",
            "Ranong", "Chumphon", "Prachuap Khiri Khan", "Hua Hin", "Cha-am",
            "Samut Prakan", "Nonthaburi", "Nakhon Pathom", "Saraburi", "Ayutthaya",
            "Lopburi", "Sing Buri", "Sakaeo", "Rayong", "Chachoengsao",
            "Chon Buri", "Chumphon", "Samui", "Phang Nga", "Krabi",


    "Andorra la Vella", "Monaco", "Liechtenstein", "San Marino", "Malta",
            "Valletta", "Rabat", "Fez", "Meknes", "Ifrane",
            "Ouarzazate", "Dakhla", "Laayoune", "El Jadida", "Essaouira",
            "Safi", "Azemmour", "Sale", "Temara", "Kenitra",
            "Fes", "Tangier", "Chefchaouen", "Meknes", "Rabat",
            "Marrakech", "Casablanca", "Agadir", "Tatooine", "Essaouira",
            "Marrakech", "Fez", "Tangier", "Meknes", "Rabat",
            "Tunis", "Sfax", "Sousse", "Kairouan", "Tozeur",
            "Djerba", "Gafsa", "Gafsa", "Gabès", "Medenine",
            "Monastir", "Hammamet", "Nabeul", "Testour", "Makthar",
            "Algiers", "Oran", "Blida", "Tlemcen", "Bejaia",
            "Constantina", "Setif", "Sidi Bel Abbes", "Mascara", "Tiaret",
            "Laghouat", "Biskra", "Tamanrasset", "In Salah", "In Amenas",
            "Ghardaia", "Ouargla", "Hassi Messaoud", "Beni Abbes", "Tindouf",
            "Djanet", "Illizi", "Tinzouan", "Araouane", "Araouane",
            "Cairo", "Giza", "Alexandria", "Aswan", "Luxor",
            "Hurghada", "Sharm El-Sheikh", "Dahab", "Nuweiba", "Taba",
            "Port Said", "Suez", "Ismailia", "Mansoura", "Tanta",
            "Zagazig", "Benha", "Shibin El Kom", "Kafr El Zayat", "Minyat El Qamh",
            "Damietta", "Port Fouad", "Rosetta", "Desuk", "Rashid",
            "Kafr El Sheikh", "Kafr El Dawar", "Rosetta", "Kafr Shukri", "Gembok",
            "Minia", "Assiut", "Sohag", "Asyut", "Qena",
            "Luxor", "Karnak", "Thebes", "Valley of the Kings", "Dendera",
            "Abydos", "Aswan", "Abu Simbel", "Philae", "Elephantine",
    };
}
